name: personnummer
version: 1.0.2
description: Validate Swedish social security numbers with Dart and Flutter.
author: Fredrik Forsmo <fredrik.forsmo@gmail.com>
homepage: https://github.com/personnummer/dart

environment:
  sdk: ">=2.0.0 <3.0.0"

dev_dependencies:
  test: ^1.3.4