name: personnummer
version: 1.0.0
description: Validate Swedish social security numbers
homepage: https://github.com/personnummer/dart

environment:
  sdk: ">=2.0.0 <3.0.0"

dev_dependencies:
  test: ^1.3.4